###
GET http://localhost:3000

###
GET http://localhost:3000/partners

###
POST http://localhost:3000/partners
Content-Type: application/json

{
    "name": "Partner 1"
}

###
@partner_id = 77d680fb-8829-426b-8a79-105f272ba661

###
GET http://localhost:3000/customers

###
POST http://localhost:3000/customers
Content-Type: application/json

{
    "name": "Customer 1",
    "cpf": "592.110.870-74"
}

###
@customer_id = 569c32a8-eac6-40ed-bea3-c859b15a0923

###
GET http://localhost:3000/events

###
POST http://localhost:3000/events
Content-Type: application/json

{
    "name": "Event 1",
    "description": "Description 1",
    "date": "2020-01-01T00:00:00.000Z",
    "partner_id": "{{partner_id}}"
}

###
@event_id = eb7c7d65-591f-4347-aa68-c62bb2dcbbbb

###
GET http://localhost:3000/events/{{event_id}}/sections

###
POST http://localhost:3000/events/{{event_id}}/sections
Content-Type: application/json

{
    "name": "Section 1",
    "description": "Description 1",
    "total_spots": 1,
    "price": 200
}

###
PUT http://localhost:3000/events/{{event_id}}/publish-all

###
@section_id = 506eb81b-0bdd-4277-85df-c837aaa71a4f

###
PUT http://localhost:3000/events/{{event_id}}/sections/{{section_id}}
Content-Type: application/json

{
    "name": "Section 1 updateddddd",
    "description": "Description 1 updatedddd"
}

###
GET http://localhost:3000/events/{{event_id}}/sections/{{section_id}}/spots

@spot_id = f8f3f05c-c243-4485-8d6c-e61548588814

###
PUT http://localhost:3000/events/{{event_id}}/sections/{{section_id}}/spots/{{spot_id}}
Content-Type: application/json

{
    "location": "Location 1 updateddddqqqq"
}

###
GET http://localhost:3000/events/{{event_id}}/orders

###
POST http://localhost:3000/events/{{event_id}}/orders
Content-Type: application/json

{
    "customer_id": "{{customer_id}}",
    "section_id": "{{section_id}}",
    "spot_id": "{{spot_id}}",
    "card_token": "tok_visa"
}